version: '3.8'

services:
  debugflow-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CLIENT_URL=http://localhost:5173
    ports:
      - "5173:5173"
      - "3001:3001"
      - "4173:4173"
    # Add extra capabilities if needed
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined