version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    networks:
      - debugflow-network

volumes:
  node_modules:

networks:
  debugflow-network:
    driver: bridge